'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const Assembly=require('../assembly-finance'),Finance=require('../finance-preview'),Inventory=require('../inventory-guard'),Dashboard=require('../dashboard-view');
const {state}=require('./fixtures/dashboard-state');
const html=fs.readFileSync(path.join(__dirname,'../index.html'),'utf8');
const scripts=[...html.matchAll(/<script([^>]*)>([\s\S]*?)<\/script>/g)].filter(m=>m[2].trim());
const TODAY='2026-10-07',NOW='2026-10-08T01:00:00Z';
function fixture(){const d=state();d.settings.mountings[0].rate=2.6;d.financeControl.version=1;for(const e of d.weeks['2026-10-05'].entries)if(e.mountingId==='a'&&['cabedal','palmilha','solado'].includes(e.kind))e.qty=288;return d}
function production(id='new-return',qty=144){return{id,kind:'finished',mountingId:'a',mountingName:'Montagem A (teste)',modelId:'m507',modelName:'507',line:'500',color:'Preto',qty,date:TODAY,inputQty:qty,inputUnit:'pairs',createdAt:NOW}}
function withAdvance(d=fixture()){d.factoryExpenses.push({id:'advance-exp',date:'2026-10-05',category:'Mão de obra',status:'paid',amount:200,description:'Adiantamento sintético'});d.financeControl.advances.push({id:'advance',expenseId:'advance-exp',mountingId:'a',linkedAt:NOW});return d}
function ready(d=withAdvance()){return Assembly.createFinished(d,production(),{today:TODAY,now:NOW})}
function app(input=fixture(),writeError=false){
 const nodes=new Map(),saved=[];
 function node(id){if(!nodes.has(id))nodes.set(id,{id,innerHTML:'',hidden:id==='modal',textContent:'',value:'',checked:false,dataset:{},disabled:false,setAttribute(){},addEventListener(){},querySelectorAll(selector){if(selector==='[data-assembly-obligation]')return[...this.innerHTML.matchAll(/data-assembly-obligation="([^"]+)" checked/g)].map(m=>{const n=node('check-'+m[1]);n.checked=true;n.dataset.assemblyObligation=m[1];return n});return[]}});return nodes.get(id)}
 const FixedDate=class extends Date{constructor(...a){super(...(a.length?a:[NOW]))}static now(){return new Date(NOW).getTime()}};
 const online={hasPending:()=>false,conflict:()=>false};
 const context=vm.createContext({FioriAssembly:Assembly,FioriFinance:Finance,FioriInventory:Inventory,FioriDashboard:Dashboard,Date:FixedDate,Intl,console,setTimeout(){},clearTimeout(){},navigator:{},localStorage:{getItem:()=>JSON.stringify(input),setItem:(key,value)=>{if(writeError)throw Error("Synthetic quota exceeded");saved.push({key,value})}},document:{getElementById:node,querySelector:node,querySelectorAll(){return[]}},window:{fioriOnline:online,scrollTo(){}}});
 const main=scripts[0][2].slice(0,scripts[0][2].lastIndexOf('\ndocument.querySelectorAll("nav [role=tab]").forEach'));
 vm.runInContext(main,context);vm.runInContext(scripts.find(s=>s[2].includes('function factoryExpensesBootstrap'))[2],context);
 vm.runInContext('globalThis.api={getData:()=>data,openExpenses:()=>switchTab("expenses"),openEntry:()=>switchTab("entry"),closeModal,replaceData:(next)=>{data=next;render()},saveEntry,deleteEntry,edit:(id,weekKey)=>{ui.editingEntry={id,weekKey}},leave:()=>{ui.tab="stock"}}',context);
 function fields(values={}){for(const [id,value]of Object.entries({'entry-date':TODAY,'entry-qty':'144','entry-kind':'finished','entry-mounting':'a','entry-model':'m507','entry-unit':'pairs','entry-color':'Preto',...values}))node(id).value=value}
 function settlement(){context.api.openExpenses();for(const[id,v]of Object.entries({'assembly-date':TODAY,'assembly-mounting':'a','assembly-method':'Pix','assembly-note':''}))node(id).value=v;node('assembly-mounting').onchange()}
 return{api:context.api,node,saved,online,fields,settlement,setWriteError:value=>{writeError=value},submissionId:()=>vm.runInContext("activeEntrySubmission.id",context),rejectSaves:()=>vm.runInContext("save=()=>false",context),submitEntry:()=>context.api.saveEntry({preventDefault(){}}),submitSettlement:()=>node('assembly-settlement-form').onsubmit({preventDefault(){}})};
}
test('new finished production and pending labor expense are saved in one state',()=>{const a=app();a.fields();a.submitEntry();assert.equal(a.saved.length,1);const d=a.api.getData(),p=Assembly.obligations(d);assert.equal(p.length,1);assert.equal(p[0].grossCents,37440);assert.equal(p[0].status,'pending');assert.equal(p[0].category,'Mão de obra');assert.equal(d.financeControl.settlements.length,0);assert.equal(d.stockLedger.length,3);assert.equal(Inventory.validate(d).length,0)});
test('insufficient materials changes neither production nor expenses',()=>{const a=app(),before=JSON.stringify(a.api.getData());a.fields({'entry-qty':'1000'});a.submitEntry();assert.equal(a.saved.length,0);assert.equal(JSON.stringify(a.api.getData()),before)});
test('retroactive production without dated rate is refused atomically',()=>{const a=app(),before=JSON.stringify(a.api.getData());a.fields({'entry-date':'2026-10-06'});a.submitEntry();assert.equal(a.saved.length,0);assert.equal(JSON.stringify(a.api.getData()),before)});
test('pending, conflict, and unhydrated online sessions block a new finished record',()=>{for(const kind of ['hasPending','conflict','unhydrated']){const a=app(),before=JSON.stringify(a.api.getData());if(kind==='unhydrated'){a.online.onlineMode=true;a.online.canEditGoal=()=>false}else a.online[kind]=()=>true;a.fields();a.submitEntry();assert.equal(a.saved.length,0);assert.equal(JSON.stringify(a.api.getData()),before)}});
test('opening the new panel never backfills historical production',()=>{const d=fixture();d.weeks['2026-10-05'].entries.push({...production('historic'),mountingRate:2.6,mountingAmount:374.4});const a=app(d),before=JSON.stringify(a.api.getData());a.api.openExpenses();assert.equal(a.saved.length,0);assert.equal(JSON.stringify(a.api.getData()),before);assert.equal(a.api.getData().assemblyControl,undefined)});
test('managed finished production is protected from edit and deletion',()=>{const a=app(ready()),before=JSON.stringify(a.api.getData());a.api.edit('new-return','2026-10-05');a.fields({'entry-qty':'72'});a.submitEntry();a.api.deleteEntry('2026-10-05','new-return');assert.equal(a.saved.length,0);assert.equal(JSON.stringify(a.api.getData()),before);assert.match(a.node('toast').textContent,/não pode ser apagado/)});
test('new settlement automatically previews gross, open advance and net without saving',()=>{const a=app(ready()),before=JSON.stringify(a.api.getData());a.settlement();assert.match(a.node('assembly-preview').textContent,/374,40/);assert.match(a.node('assembly-preview').textContent,/200,00/);assert.match(a.node('assembly-preview').textContent,/174,40/);assert.equal(a.saved.length,0);assert.equal(JSON.stringify(a.api.getData()),before)});
test('settlement cancellation and retained old confirmation never save',()=>{const a=app(ready()),before=JSON.stringify(a.api.getData());a.settlement();a.submitSettlement();const confirm=a.node('modal-confirm').onclick;a.api.closeModal();confirm();assert.equal(a.saved.length,0);assert.equal(JSON.stringify(a.api.getData()),before)});
test('confirmed settlement updates obligations, allocations and net payment exactly once',()=>{const a=app(ready());a.settlement();a.submitSettlement();const confirm=a.node('modal-confirm').onclick;confirm();confirm();const d=a.api.getData();assert.equal(a.saved.length,1);assert.equal(d.financeControl.settlements.length,1);assert.equal(Assembly.obligations(d)[0].status,'paid');assert.equal(d.factoryExpenses.find(x=>x.role==='assembly_cash').amount,174.4);assert.equal(Finance.openAdvances(d,'a').length,0);const s=Assembly.expenseSummary(d,'2026-10');assert.equal(s.costCents,37440);assert.equal(s.cashCents,37440)});
test('a new settlement without advance is allowed and records the full net only once',()=>{const a=app(ready(fixture()));a.settlement();a.submitSettlement();a.node('modal-confirm').onclick();const d=a.api.getData(),x=d.financeControl.settlements[0];assert.equal(x.allocations.length,0);assert.equal(x.grossCents,37440);assert.equal(d.factoryExpenses.find(x=>x.role==='assembly_cash').amount,374.4);assert.equal(Assembly.expenseSummary(d,'2026-10').cashCents,37440)});
test('full advance coverage creates no zero-valued cash expense',()=>{const d=withAdvance();d.factoryExpenses[0].amount=500;const a=app(ready(d));a.settlement();a.submitSettlement();a.node('modal-confirm').onclick();const out=a.api.getData();assert.equal(out.factoryExpenses.filter(x=>x.role==='assembly_cash').length,0);assert.equal(out.financeControl.settlements[0].netExpenseId,null);assert.equal(Finance.openAdvances(out,'a')[0].balanceCents,12560)});
test('changed state and pending synchronization invalidate an open settlement confirmation',()=>{for(const mode of ['data','pending','conflict']){const a=app(ready());a.settlement();a.submitSettlement();if(mode==='data')a.api.getData().factoryExpenses[0].amount=100;else a.online[mode==='pending'?'hasPending':'conflict']=()=>true;a.node('modal-confirm').onclick();assert.equal(a.saved.length,0);assert.match(a.node('toast').textContent,/dados mudaram/)}});
test('leaving or rerendering expenses invalidates retained submit and confirm callbacks',()=>{const a=app(ready());a.settlement();const oldSubmit=a.node('assembly-settlement-form').onsubmit;a.api.leave();oldSubmit({preventDefault(){}});assert.equal(a.saved.length,0);a.settlement();a.submitSettlement();const confirm=a.node('modal-confirm').onclick;a.api.openExpenses();confirm();assert.equal(a.saved.length,0)});
test('future settlement is not recorded',()=>{const a=app(ready());a.settlement();a.node('assembly-date').value='2026-10-08';a.node('assembly-date').onchange();a.submitSettlement();assert.equal(a.saved.length,0);assert.match(a.node('toast').textContent,/já realizado/)});
test('new accounting labels distinguish gross cost, pending gross and cash paid',()=>{const a=app(ready());a.api.openExpenses();const text=a.node('tab-expenses').innerHTML;for(const label of ['Custo lançado','Custo quitado','Pendente bruto','Pago no caixa'])assert.ok(text.includes(label),label);assert.match(text,/Adiantamentos e pagamentos líquidos entram em Pago no caixa/)});
test('editing an existing component cannot transform it into new managed production',()=>{const a=app(),before=JSON.stringify(a.api.getData());a.api.edit('fixture-1','2026-10-05');a.fields();a.submitEntry();assert.equal(a.saved.length,0);assert.equal(JSON.stringify(a.api.getData()),before);assert.match(a.node('toast').textContent,/novo lançamento/)});
test('a stale edit target cannot create a replacement finished entry',()=>{const a=app(),before=JSON.stringify(a.api.getData());a.api.edit('missing','2026-10-05');a.fields();a.submitEntry();assert.equal(a.saved.length,0);assert.equal(JSON.stringify(a.api.getData()),before)});
test('repeated production submit reuses one operation and cannot add a second obligation',()=>{const a=app();a.fields();a.submitEntry();a.submitEntry();const d=a.api.getData();assert.equal(a.saved.length,1);assert.equal(Assembly.obligations(d).length,1);assert.equal(d.weeks['2026-10-05'].entries.filter(x=>x.kind==='finished').length,1)});
test('retained production form callback is ignored after leaving or rerendering entry',()=>{const a=app();a.api.openEntry();a.fields();const old=a.node('entry-form').onsubmit;a.api.leave();old({preventDefault(){}});assert.equal(a.saved.length,0);a.api.openEntry();a.fields();old({preventDefault(){}});assert.equal(a.saved.length,0);const current=a.node('entry-form').onsubmit;current({preventDefault(){}});current({preventDefault(){}});assert.equal(a.saved.length,1)});
test('failed local production persistence rolls back and allows retry with the same operation ID',()=>{const a=app(fixture(),true),before=JSON.stringify(a.api.getData());a.fields();a.submitEntry();const id=a.submissionId();assert.equal(a.saved.length,0);assert.equal(JSON.stringify(a.api.getData()),before);assert.match(a.node('toast').textContent,/não foi salvo/);a.setWriteError(false);a.submitEntry();assert.equal(a.saved.length,1);assert.equal(Assembly.obligations(a.api.getData())[0].productionEntryId,id)});
test('failed local settlement persistence leaves obligation pending and advances untouched',()=>{const a=app(ready(),true),before=JSON.stringify(a.api.getData());a.settlement();a.submitSettlement();a.node('modal-confirm').onclick();assert.equal(a.saved.length,0);assert.equal(JSON.stringify(a.api.getData()),before);assert.match(a.node('toast').textContent,/não foi salvo/);a.setWriteError(false);a.submitSettlement();a.node('modal-confirm').onclick();assert.equal(a.saved.length,1);assert.equal(a.api.getData().financeControl.settlements.length,1)});
test('explicit save rejection rolls back new production and settlement clones',()=>{const a=app(),b=app(ready());for(const [x,kind]of [[a,'production'],[b,'settlement']]){const before=JSON.stringify(x.api.getData());x.rejectSaves();if(kind==='production'){x.fields();x.submitEntry()}else{x.settlement();x.submitSettlement();x.node('modal-confirm').onclick()}assert.equal(x.saved.length,0);assert.equal(JSON.stringify(x.api.getData()),before)}});
test('assembly module and new cache shell are present for offline use',()=>{assert.match(html,/<script src="assembly-finance\.js\?v=30"><\/script>/);const sw=fs.readFileSync(path.join(__dirname,'../sw.js'),'utf8');assert.match(sw,/shell-v31/);assert.match(sw,/"\.\/assembly-finance\.js\?v=30"/)});
