'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const {state}=require('./fixtures/dashboard-state');
const html=fs.readFileSync(path.join(__dirname,'../index.html'),'utf8');
const scripts=[...html.matchAll(/<script([^>]*)>([\s\S]*?)<\/script>/g)].filter(m=>m[2].trim());
const STORAGE='acompanhar_producao_v2',PENDING='acompanhar_producao_remote_pending_v2',CONFLICT='acompanhar_producao_remote_conflict_v1',ORPHAN='acompanhar_producao_presync_recovery_v1',WEEK='2026-10-05';
const clone=x=>JSON.parse(JSON.stringify(x)),tick=()=>new Promise(resolve=>setImmediate(resolve));
function row(goal=1200,revision=39){const data=state();data.onboardingDone=false;data.weeks[WEEK].goal=goal;return{data,revision,updated_at:'2026-10-08T00:00:00Z'}}
function deferred(){let resolve;const promise=new Promise(r=>resolve=r);return{promise,resolve}}
function app({remote=row(),local=null,session=null,pending=null,readError=null,missingSdk=false,writeErrorKey=null,firstSessionRead=null}={}){
 const nodes=new Map(),storage=new Map(),writes=[],rpcs=[],timers=new Map(),events=new Map();let timerId=0,authListener,realtime,reads=0,readOverride=null,rpcOverride=null,signInOverride=null,sessionOverride=null,sessionReads=0,signIns=0;
 if(local)storage.set(STORAGE,JSON.stringify(local));if(pending)storage.set(PENDING,JSON.stringify(pending));
 const classList=()=>{const values=new Set();return{add:x=>values.add(x),remove:x=>values.delete(x),contains:x=>values.has(x),toggle(x,on){if(on)values.add(x);else values.delete(x)}}};
 const node=id=>{if(!nodes.has(id))nodes.set(id,{innerHTML:'',hidden:id==='modal',textContent:'',value:'',disabled:false,classList:classList(),setAttribute(){},querySelectorAll(){return[]},addEventListener(){}});return nodes.get(id)};
 const body={classList:classList()};body.classList.add('remote-lock');
 const sb={auth:{getSession:async()=>{sessionReads++;if(sessionOverride)return sessionOverride();if(sessionReads===1&&firstSessionRead)return firstSessionRead;return{data:{session}}},signInWithPassword:async()=>{signIns++;if(signInOverride)return signInOverride();session={user:{id:'synthetic-owner'}};return{error:null}},signOut:async()=>{session=null;authListener?.('SIGNED_OUT',null);return{}},onAuthStateChange(fn){authListener=fn;return{data:{subscription:{unsubscribe(){}}}}}},
 from(){return{select(){return this},eq(){return this},async single(){reads++;if(readOverride)return readOverride();return{data:clone(remote),error:readError}}}},
 channel(){return{on(_event,_filter,fn){realtime=fn;return this},subscribe(){return this}}},
 async rpc(name,args){rpcs.push({name,args:clone(args)});if(rpcOverride)return rpcOverride(name,args);if(args.p_expected_revision!==remote.revision)return{data:null,error:{message:'revision conflict'}};remote={data:clone(args.p_data),revision:remote.revision+1};return{data:[{new_revision:remote.revision}],error:null}}};
 const FixedDate=class extends Date{constructor(...args){super(...(args.length?args:['2026-10-08T01:00:00Z']))}static now(){return new Date('2026-10-08T01:00:00Z').getTime()}};
 const window={scrollTo(){},addEventListener(name,fn){events.set(name,fn)},...(missingSdk?{}:{supabase:{createClient:()=>sb}})};
 const context=vm.createContext({FioriAssembly:require('../assembly-finance'),FioriInventory:require('../inventory-guard'),FioriDashboard:require('../dashboard-view'),FioriFinance:require('../finance-preview'),FioriFulfillment:require('../order-fulfillment'),Date:FixedDate,Intl,console,navigator:{onLine:true},
 setTimeout(fn,delay){timers.set(++timerId,{fn,delay});return timerId},clearTimeout(id){timers.delete(id)},
 localStorage:{getItem:key=>storage.get(key)??null,setItem(key,value){if(key===writeErrorKey)throw new Error("Synthetic quota exceeded");storage.set(key,String(value));writes.push({key,value:String(value)})},removeItem(key){storage.delete(key)}},
 document:{body,getElementById:node,querySelector:node,querySelectorAll(selector){if(selector==='[data-define-rate]')return ['a','b','empty'].map(id=>{const button=node('rate-button-'+id);button.dataset={defineRate:id};return button});return[]}},window,location:{reload(){}}});
 const main=scripts[0][2].slice(0,scripts[0][2].lastIndexOf('\ndocument.querySelectorAll("nav [role=tab]").forEach'));
 vm.runInContext(main,context);for(const script of scripts.slice(1).filter(m=>!m[1].includes('remote-sync-v2')))vm.runInContext(script[2],context);
 vm.runInContext('render();globalThis.testApi={settings:()=>switchTab("settings"),openRate:()=>openMountingRate("a"),getData:()=>data,save:()=>save(),onboarding:()=>onboarding(),goalModal:()=>goalModal(),closeModal:()=>closeModal(),showModal:(text)=>showModal(text),getGoalDialog:()=>goalDialog,getDialogVersion:()=>goalDialogVersion,ensureWeek:(key)=>ensureWeek(key)}',context);
 vm.runInContext(scripts.find(m=>m[1].includes('remote-sync-v2'))[2],context);
 return{api:context.testApi,node,storage,writes,rpcs,timers,body,online:()=>window.fioriOnline,getRemote:()=>clone(remote),getReads:()=>reads,
 async ready(){await tick();await tick()},async login(){node('remote-email').value='synthetic@example.invalid';node('remote-password').value='synthetic-password';await node('remote-login-form').onsubmit({preventDefault(){}});await tick()},
 setWriteErrorKey(key){writeErrorKey=key},setSessionRead(fn){sessionOverride=fn},getSignIns:()=>signIns,setSignIn(fn){signInOverride=fn},setRpc(fn){rpcOverride=fn},setRead(fn){readOverride=fn},setReadError(error){readError=error},setRemote(next){remote=clone(next)},setSession(next){session=next},signOut(){session=null;authListener?.('SIGNED_OUT',null)},emit(next){remote=clone(next);realtime?.({new:clone(next)})},async focus(){await events.get('focus')?.()},
 async begin(goal='777'){node('first-goal').value=goal;await node('start-app').onclick()},async flush(){await window.fioriOnline.flush()},async runTimers(){const pending=[...timers.values()];timers.clear();for(const {fn} of pending)await fn();await tick()}};
}
const authenticated={user:{id:'synthetic-owner'}};
test('startup never schedules local onboarding and login CSS hides every modal',()=>{assert.doesNotMatch(scripts[0][2],/setTimeout\(onboarding/);assert.match(html,/\.remote-lock \.wrap,\.remote-lock #modal\{display:none\}/)});
test('fresh device stays on login, does not open goals or persist defaults',async()=>{const a=app();await a.ready();a.api.onboarding();a.api.goalModal();a.api.save();await a.flush();await a.runTimers();assert.equal(a.node('modal').hidden,true);assert.equal(a.body.classList.contains('remote-lock'),true);assert.equal(a.getReads(),0);assert.equal(a.writes.length,0);assert.equal(a.rpcs.length,0)});
test('existing online goal wins over stale local goal and onboarding flag',async()=>{const local=row(9999).data,a=app({local,remote:row(1200)});await a.ready();await a.login();assert.equal(a.node('modal').hidden,true);assert.equal(a.api.getData().weeks[WEEK].goal,1200);assert.equal(a.rpcs.length,0);assert.equal(a.online().canEditGoal(),true);assert.equal(a.online().needsGoal(WEEK),false)});
test('saved session waits for remote hydration before allowing any goal or save',async()=>{const d=deferred(),a=app({session:authenticated});a.setRead(()=>d.promise);await a.ready();a.api.onboarding();a.api.goalModal();a.api.save();await a.flush();assert.equal(a.node('modal').hidden,true);assert.equal(a.writes.length,0);assert.equal(a.rpcs.length,0);d.resolve({data:row(1400),error:null});await a.ready();assert.equal(a.body.classList.contains('remote-lock'),false);assert.equal(a.api.getData().weeks[WEEK].goal,1400)});
test('no weekly goal opens onboarding only after successful login and online read',async()=>{const remote=row(null);remote.data.onboardingDone=true;const a=app({remote});await a.ready();assert.equal(a.node('modal').hidden,true);await a.login();assert.match(a.node('modal-sheet').innerHTML,/Comece pela meta/);assert.equal(a.body.classList.contains('remote-lock'),false);assert.equal(a.rpcs.length,0)});
test('previous week goal is not inherited or treated as a current online goal',async()=>{const remote=row(500);remote.data.weeks['2026-09-28']=clone(remote.data.weeks[WEEK]);delete remote.data.weeks[WEEK];const a=app({remote,session:authenticated});await a.ready();assert.equal(a.api.getData().weeks[WEEK].goal,null);assert.equal(a.node('modal').hidden,false);assert.equal(a.rpcs.length,0);assert.equal(a.getRemote().data.weeks[WEEK],undefined)});
test('offline/error is unknown, keeps login visible, and never writes',async()=>{const a=app({session:authenticated,remote:row(null),readError:{message:'network down'}});await a.ready();a.api.onboarding();a.api.save();await a.flush();assert.equal(a.node('modal').hidden,true);assert.equal(a.body.classList.contains('remote-lock'),true);assert.equal(a.writes.length,0);assert.equal(a.rpcs.length,0);assert.match(a.node('remote-auth-msg').textContent,/conexão/)});
test('malformed or missing rows never become missing-goal onboarding',async()=>{for(const remote of [null,{data:null,revision:39},{data:[],revision:39},{data:{},revision:39},{data:{weeks:[]},revision:39}]){const a=app({session:authenticated,remote});await a.ready();assert.equal(a.node('modal').hidden,true);assert.equal(a.online().canEditGoal(),false);assert.equal(a.rpcs.length,0)}});
test('missing SDK fails closed with an actionable login message',async()=>{const a=app({missingSdk:true});await a.ready();a.api.onboarding();assert.equal(a.node('modal').hidden,true);assert.match(a.node('remote-auth-msg').textContent,/recarregue/);assert.equal(a.rpcs.length,0)});
test('initial goal rereads online state and preserves existing operational arrays',async()=>{const remote=row(null),before=clone(remote.data),a=app({remote,session:authenticated});await a.ready();await a.begin('777');assert.equal(a.getReads(),2);assert.equal(a.node('modal').hidden,true);await a.flush();assert.equal(a.rpcs.length,1);assert.equal(a.getRemote().data.weeks[WEEK].goal,777);for(const key of ['stockLedger','factoryExpenses'])assert.deepEqual(a.getRemote().data[key],before[key]);assert.deepEqual(a.getRemote().data.weeks[WEEK].entries,before.weeks[WEEK].entries)});
test('a goal arriving just before submit is adopted without any RPC overwrite',async()=>{const a=app({remote:row(null),session:authenticated});await a.ready();a.setRemote(row(2200,40));await a.begin();await a.flush();assert.equal(a.rpcs.length,0);assert.equal(a.api.getData().weeks[WEEK].goal,2200);assert.equal(a.node('modal').hidden,true)});
test('online change with no goal cancels stale submit and keeps new state intact',async()=>{const a=app({remote:row(null),session:authenticated});await a.ready();const next=row(null,40);next.data.auditMarker='new remote data';a.setRemote(next);await a.begin();await a.flush();assert.equal(a.rpcs.length,0);assert.equal(a.api.getData().auditMarker,'new remote data');assert.equal(a.api.getData().weeks[WEEK].goal,null)});
test('fresh goal verification failure does not mutate local state or write',async()=>{const a=app({remote:row(null),session:authenticated});await a.ready();const before=JSON.stringify(a.api.getData());a.setReadError({message:'offline'});await a.begin();assert.equal(JSON.stringify(a.api.getData()),before);assert.equal(a.rpcs.length,0);assert.equal(a.node('modal').hidden,false);assert.equal(a.node('start-app').disabled,false)});
test('realtime saved goal closes onboarding and preserves the online goal',async()=>{const a=app({remote:row(null),session:authenticated});await a.ready();a.emit(row(1800,40));assert.equal(a.node('modal').hidden,true);assert.equal(a.api.getData().weeks[WEEK].goal,1800);assert.equal(a.rpcs.length,0)});
test('remote refresh leaves unrelated receipt modal open',async()=>{const a=app({session:authenticated});await a.ready();a.api.showModal('Synthetic receipt');a.emit(row(1800,40));assert.equal(a.node('modal').hidden,false);assert.equal(a.node('modal-sheet').innerHTML,'Synthetic receipt')});
test('dismissed onboarding is not reopened on later remote updates or focus',async()=>{const a=app({remote:row(null),session:authenticated});await a.ready();a.api.closeModal();a.emit(row(null,40));await a.focus();assert.equal(a.node('modal').hidden,true);assert.equal(a.rpcs.length,0)});
test('auth loss closes goal dialog synchronously and blocks later saves',async()=>{const a=app({remote:row(null),session:authenticated});await a.ready();const writes=a.writes.length;a.signOut();assert.equal(a.node('modal').hidden,true);assert.equal(a.body.classList.contains('remote-lock'),true);a.api.save();await a.flush();assert.equal(a.writes.length,writes);assert.equal(a.rpcs.length,0)});
test('sign-out during initial fetch cannot unlock or prompt after response',async()=>{const d=deferred(),a=app({session:authenticated});a.setRead(()=>d.promise);await a.ready();a.signOut();d.resolve({data:row(null),error:null});await a.ready();assert.equal(a.body.classList.contains('remote-lock'),true);assert.equal(a.node('modal').hidden,true);assert.equal(a.writes.length,0)});
test('sign-out during goal verification cancels submission',async()=>{const a=app({remote:row(null),session:authenticated});await a.ready();const d=deferred();a.setRead(()=>d.promise);const submit=a.begin();await a.ready();a.signOut();d.resolve({data:row(null),error:null});await submit;await a.flush();assert.equal(a.rpcs.length,0);assert.equal(a.api.getData().weeks[WEEK].goal,null)});
test('dismissal during verification cancels save even if a new goal dialog opens',async()=>{const a=app({remote:row(null),session:authenticated});await a.ready();const d=deferred();a.setRead(()=>d.promise);const submit=a.begin();await a.ready();a.api.closeModal();a.api.onboarding();d.resolve({data:row(null),error:null});await submit;await a.flush();assert.equal(a.rpcs.length,0);assert.equal(a.api.getData().weeks[WEEK].goal,null)});
test('repeated initial-goal clicks produce one write',async()=>{const a=app({remote:row(null),session:authenticated});await a.ready();const d=deferred();a.setRead(()=>d.promise);const first=a.begin(),second=a.begin();await a.ready();assert.equal(a.getReads(),2);d.resolve({data:row(null),error:null});await Promise.all([first,second]);await a.flush();assert.equal(a.rpcs.length,1)});
test('session expiry detected on submit closes onboarding without changing goal',async()=>{const a=app({remote:row(null),session:authenticated});await a.ready();a.setSession(null);await a.begin();assert.equal(a.rpcs.length,0);assert.equal(a.node('modal').hidden,true);assert.equal(a.body.classList.contains('remote-lock'),true)});
test('revision CAS still protects a concurrent goal saved after the verification read',async()=>{const a=app({remote:row(null),session:authenticated});await a.ready();await a.begin('777');a.setRemote(row(2000,40));await a.flush();assert.equal(a.getRemote().data.weeks[WEEK].goal,2000);assert.equal(a.online().conflict(),true);assert.ok(a.storage.get(CONFLICT));assert.match(a.node('modal-sheet').innerHTML,/Conflito protegido/)});
test('pre-sync pending is quarantined rather than sent even at online revision zero',async()=>{for(const revision of [0,39]){const pending={data:row(9999).data,baseRevision:0,localVersion:1},a=app({remote:row(1200,revision),local:pending.data,pending,session:authenticated});await a.ready();await a.runTimers();assert.equal(a.rpcs.length,0);assert.equal(a.api.getData().weeks[WEEK].goal,1200);assert.ok(a.storage.get(ORPHAN));assert.equal(a.storage.has(PENDING),false)}});
test('real pending change is restored and sent only after confirmed hydration',async()=>{const remote=row(1200),pending={data:clone(remote.data),baseRevision:39,localVersion:1};pending.data.auditMarker='synthetic pending';const d=deferred(),a=app({remote,pending,session:authenticated});a.setRead(()=>d.promise);await a.ready();await a.flush();assert.equal(a.rpcs.length,0);d.resolve({data:remote,error:null});await a.ready();await a.runTimers();assert.equal(a.rpcs.length,1);assert.equal(a.getRemote().data.auditMarker,'synthetic pending');assert.equal(a.node('modal').hidden,true)});
test('pending conflict is preserved and never covered by onboarding',async()=>{const pending={data:row(800).data,baseRevision:38,localVersion:1},a=app({remote:row(null),pending,session:authenticated});await a.ready();await a.flush();assert.equal(a.rpcs.length,0);assert.equal(a.online().canEditGoal(),false);assert.match(a.node('modal-sheet').innerHTML,/Conflito protegido/)});
test('manual Editar meta is available only after hydration, and remote updates dismiss stale edits',async()=>{const a=app({session:authenticated});await a.ready();a.api.goalModal();assert.match(a.node('modal-sheet').innerHTML,/Meta da semana/);a.emit(row(2300,40));assert.equal(a.node('modal').hidden,true);assert.equal(a.api.getData().weeks[WEEK].goal,2300)});

test('trusted revision-zero pending remains retryable and is never quarantined',async()=>{const remote=row(null,0),pending={data:row(777,0).data,hydrated:true,baseRevision:0,localVersion:1},a=app({remote,pending,session:authenticated});await a.ready();await a.flush();assert.equal(a.rpcs.length,1);assert.equal(a.getRemote().data.weeks[WEEK].goal,777);assert.equal(a.storage.has(ORPHAN),false)});
test('new goal pending records establish hydration provenance',async()=>{const a=app({remote:row(null,0),session:authenticated});await a.ready();await a.begin();const pending=JSON.parse(a.storage.get(PENDING));assert.equal(pending.hydrated,true);assert.equal(pending.baseRevision,0)});
test('failed presync archival preserves pending and enters protected conflict',async()=>{const pending={data:row(9999).data,baseRevision:0,localVersion:1},a=app({remote:row(1200),pending,session:authenticated,writeErrorKey:ORPHAN});await a.ready();await a.flush();assert.equal(a.rpcs.length,0);assert.deepEqual(JSON.parse(a.storage.get(PENDING)),pending);assert.equal(a.online().conflict(),true)});
test('presync archival retains prior recovery records',async()=>{const pending={data:row(9999).data,baseRevision:0,localVersion:1},a=app({pending,session:authenticated});a.storage.set(ORPHAN,'{"prior":"synthetic recovery"}');await a.ready();assert.equal(JSON.parse(a.storage.get(ORPHAN)).previousArchive,'{"prior":"synthetic recovery"}')});
test('stale refresh after logout and a newer login cannot replace the online goal',async()=>{const a=app({remote:row(100,1),session:authenticated});await a.ready();const d=deferred();a.setRead(()=>d.promise);const stale=a.online().refresh();await a.ready();a.signOut();a.setRead(null);a.setRemote(row(500,3));await a.login();d.resolve({data:row(null,2),error:null});await stale;assert.equal(a.api.getData().weeks[WEEK].goal,500);assert.equal(a.node('modal').hidden,true)});
test('stale focus read after logout cannot replace a newer login',async()=>{const a=app({remote:row(100,1),session:authenticated});await a.ready();const d=deferred();a.setRead(()=>d.promise);const stale=a.focus();await a.ready();a.signOut();a.setRead(null);a.setRemote(row(500,3));await a.login();d.resolve({data:row(null,4),error:null});await stale;assert.equal(a.api.getData().weeks[WEEK].goal,500);assert.equal(a.node('modal').hidden,true)});
test('refresh cannot regress a revision after realtime delivers newer state',async()=>{const a=app({remote:row(100,1),session:authenticated});await a.ready();const d=deferred();a.setRead(()=>d.promise);const stale=a.online().refresh();a.emit(row(500,3));d.resolve({data:row(null,2),error:null});await stale;assert.equal(a.api.getData().weeks[WEEK].goal,500);assert.equal(a.node('modal').hidden,true)});
test('stale RPC completion cannot clear a protected pending from a newer login',async()=>{const a=app({remote:row(null,39),session:authenticated});await a.ready();await a.begin('777');const pending=a.storage.get(PENDING),d=deferred();a.setRpc(()=>d.promise);const stale=a.flush();await a.ready();const protectedPending=a.storage.get(PENDING);a.signOut();a.setRemote(row(2000,41));await a.login();assert.equal(a.online().conflict(),true);d.resolve({data:[{new_revision:40}],error:null});await stale;assert.equal(a.storage.get(PENDING),protectedPending);assert.deepEqual(JSON.parse(protectedPending).data,JSON.parse(pending).data);assert.equal(a.online().conflict(),true);assert.equal(a.getRemote().data.weeks[WEEK].goal,2000);assert.match(a.node('modal-sheet').innerHTML,/Conflito protegido/)});
test('thrown network failure during RPC preserves pending without unhandled rejection',async()=>{const a=app({remote:row(null),session:authenticated});await a.ready();await a.begin();a.setRpc(()=>{throw new Error('Synthetic network failure')});await a.flush();assert.equal(a.online().hasPending(),true);assert.match(a.node('header-status').textContent,/pendente/)});

test('old initial-session response cannot restart hydration after an explicit login',async()=>{const d=deferred(),a=app({firstSessionRead:d.promise});await a.login();const reads=a.getReads();d.resolve({data:{session:authenticated}});await a.ready();assert.equal(a.getReads(),reads);assert.equal(a.api.getData().weeks[WEEK].goal,1200);assert.equal(a.node('modal').hidden,true)});
test('old load failure after logout cannot lock a newer successful login',async()=>{const d=deferred(),a=app({session:authenticated});a.setRead(()=>d.promise);await a.ready();a.signOut();a.setRead(null);a.setRemote(row(2000,40));await a.login();d.resolve({data:null,error:{message:'old failed read'}});await a.ready();assert.equal(a.body.classList.contains('remote-lock'),false);assert.equal(a.api.getData().weeks[WEEK].goal,2000)});
test('repeated login clicks start only one authentication request',async()=>{const d=deferred(),a=app();await a.ready();a.setSignIn(()=>d.promise);const first=a.login(),second=a.login();await a.ready();assert.equal(a.getSignIns(),1);d.resolve({error:{message:'synthetic wrong password'}});await Promise.all([first,second]);assert.equal(a.node('modal').hidden,true);assert.equal(a.rpcs.length,0)});
test('thrown authentication failure leaves a usable login and no modal',async()=>{const a=app();await a.ready();a.setSignIn(()=>{throw Error('synthetic offline')});await a.login();assert.equal(a.body.classList.contains('remote-lock'),true);assert.equal(a.node('modal').hidden,true);assert.match(a.node('remote-auth-msg').textContent,/conexão/);assert.equal(a.rpcs.length,0)});

test('stale null-session response from an old goal submit cannot lock a newer login',async()=>{const a=app({remote:row(null),session:authenticated});await a.ready();const d=deferred();a.setSessionRead(()=>d.promise);const stale=a.begin();await a.ready();a.signOut();a.setSessionRead(null);a.setRemote(row(2000,40));await a.login();d.resolve({data:{session:null}});await stale;assert.equal(a.body.classList.contains('remote-lock'),false);assert.equal(a.api.getData().weeks[WEEK].goal,2000);assert.equal(a.node('modal').hidden,true);assert.equal(a.rpcs.length,0)});
function reverseKeys(value){if(Array.isArray(value))return value.map(reverseKeys);if(value&&typeof value==='object')return Object.fromEntries(Object.keys(value).reverse().map(k=>[k,reverseKeys(value[k])]));return value}
test('lost RPC response is acknowledged by readback without a duplicate write or false conflict',async()=>{const a=app({session:authenticated});await a.ready();a.api.getData().syntheticOperation='one';a.api.save();a.setRpc(async(_name,args)=>{a.setRemote({data:reverseKeys(args.p_data),revision:40});throw Error('response lost after commit')});await a.flush();assert.equal(a.online().hasPending(),true);assert.equal(a.rpcs.length,1);a.setRpc(null);await a.flush();assert.equal(a.rpcs.length,1);assert.equal(a.online().hasPending(),false);assert.equal(a.online().conflict(),false);assert.equal(a.getRemote().revision,40);assert.equal(a.api.getData().syntheticOperation,'one')});
test('lost-response recovery retains a newer local intent and sends it at the acknowledged revision',async()=>{const a=app({session:authenticated});await a.ready();a.api.getData().syntheticOperation='one';a.api.save();const d=deferred();a.setRpc(async(_name,args)=>{a.setRemote({data:clone(args.p_data),revision:40});await d.promise;throw Error('lost')});const first=a.flush();await a.ready();a.api.getData().syntheticLater='two';a.api.save();d.resolve();await first;assert.equal(JSON.parse(a.storage.get(PENDING)).localVersion,2);assert.ok(JSON.parse(a.storage.get(PENDING)).lastSent);a.setRpc(null);await a.flush();assert.equal(a.rpcs.length,2);assert.equal(a.rpcs[1].args.p_expected_revision,40);assert.equal(a.getRemote().revision,41);assert.equal(a.getRemote().data.syntheticOperation,'one');assert.equal(a.getRemote().data.syntheticLater,'two');assert.equal(a.online().conflict(),false);assert.equal(a.online().hasPending(),false)});
test('reload with persisted last-sent receipt rebases newer local intent without overwriting online',async()=>{const remote=row(1200,40),local=clone(remote.data);local.syntheticLater='two';const pending={data:local,hydrated:true,baseRevision:39,localVersion:2,lastSent:{data:reverseKeys(remote.data),baseRevision:39,localVersion:1}},a=app({remote,pending,session:authenticated});await a.ready();assert.equal(a.online().conflict(),false);assert.equal(a.online().hasPending(),true);await a.flush();assert.equal(a.rpcs.length,1);assert.equal(a.rpcs[0].args.p_expected_revision,40);assert.equal(a.getRemote().data.syntheticLater,'two');assert.equal(a.online().hasPending(),false)});
test('failed send with no commit safely retries and a genuinely different online state stays protected',async()=>{for(const changed of [false,true]){const a=app({session:authenticated});await a.ready();a.api.getData().syntheticOperation='one';a.api.save();a.setRpc(()=>{throw Error('network before commit')});await a.flush();if(changed)a.setRemote(row(2500,40));a.setRpc(null);await a.flush();if(changed){assert.equal(a.rpcs.length,1);assert.equal(a.online().conflict(),true);assert.ok(a.storage.get(PENDING));assert.equal(a.getRemote().data.weeks[WEEK].goal,2500)}else{assert.equal(a.rpcs.length,2);assert.equal(a.online().hasPending(),false);assert.equal(a.getRemote().data.syntheticOperation,'one')}}});
test('a revision-conflict response matching the submitted payload is an acknowledgment even with reordered keys',async()=>{const a=app({session:authenticated});await a.ready();a.api.getData().syntheticOperation='one';a.api.save();a.setRpc((_name,args)=>{a.setRemote({data:reverseKeys(args.p_data),revision:40});return{data:null,error:{message:'revision conflict'}}});await a.flush();assert.equal(a.rpcs.length,1);assert.equal(a.online().hasPending(),false);assert.equal(a.online().conflict(),false)});
test('pending queue failure refuses save before changing durable cache or issuing RPC',async()=>{const a=app({session:authenticated});await a.ready();const old=a.storage.get(STORAGE);a.setWriteErrorKey(PENDING);a.api.getData().syntheticOperation='one';assert.equal(a.api.save(),false);assert.equal(a.storage.get(STORAGE),old);assert.equal(a.storage.has(PENDING),false);await a.flush();assert.equal(a.rpcs.length,0)});
test('cache failure after durable queue save keeps intent recoverable and pending until RPC acknowledgment',async()=>{const a=app({session:authenticated});await a.ready();a.setWriteErrorKey(STORAGE);a.api.getData().syntheticOperation='one';assert.equal(a.api.save(),true);assert.equal(a.online().hasPending(),true);assert.equal(JSON.parse(a.storage.get(PENDING)).data.syntheticOperation,'one');assert.equal(a.rpcs.length,0);assert.match(a.node('header-status').textContent,/Aguardando confirmação/);a.setWriteErrorKey(null);await a.flush();assert.equal(a.getRemote().data.syntheticOperation,'one');assert.equal(a.online().hasPending(),false);assert.equal(a.rpcs.length,1)});
test('cache failure during lost-response readback never leaves remote-apply mode stuck',async()=>{const a=app({session:authenticated});await a.ready();a.api.getData().syntheticOperation='one';a.api.save();a.setRpc((_name,args)=>{a.setRemote({data:clone(args.p_data),revision:40});throw Error('lost')});await a.flush();a.setWriteErrorKey(STORAGE);a.setRpc(null);await a.flush();assert.equal(a.online().hasPending(),false);assert.equal(a.online().conflict(),false);assert.equal(a.api.getData().syntheticOperation,'one');a.setWriteErrorKey(null);a.api.getData().syntheticLater='two';assert.equal(a.api.save(),true);assert.equal(a.online().hasPending(),true);await a.flush();assert.equal(a.getRemote().revision,41);assert.equal(a.getRemote().data.syntheticLater,'two');assert.equal(a.online().hasPending(),false)});
test('pending hydration with unavailable cache remains retryable and does not disable later saves',async()=>{const remote=row(1200,39),pending={data:clone(remote.data),hydrated:true,baseRevision:39,localVersion:1};pending.data.syntheticOperation='one';const a=app({remote,pending,session:authenticated,writeErrorKey:STORAGE});await a.ready();assert.equal(a.api.getData().syntheticOperation,'one');assert.equal(a.online().hasPending(),true);a.setWriteErrorKey(null);await a.flush();a.api.getData().syntheticLater='two';assert.equal(a.api.save(),true);assert.equal(a.online().hasPending(),true);await a.flush();assert.equal(a.getRemote().data.syntheticLater,'two')});

test('successful online rate acknowledgment unlocks controls without replacing other settings edits',async()=>{const a=app({session:authenticated});await a.ready();a.api.settings();a.api.openRate();a.node('mounting-rate-date').value='2026-10-07';a.node('mounting-rate-value').value='2,75';a.node('mounting-rate-form').onsubmit({preventDefault(){}});a.node('mounting-rate-confirm').onclick();assert.equal(a.online().hasPending(),true);assert.equal(a.node('rate-button-a').disabled,true);a.node('pairs-sheet').value='144';await a.flush();assert.equal(a.online().hasPending(),false);assert.equal(a.node('rate-button-a').disabled,false);assert.equal(a.node('mounting-rate-online-warning').hidden,true);assert.equal(a.node('pairs-sheet').value,'144');assert.match(a.node('header-status').textContent,/confirmada/);assert.equal(a.getRemote().data.settings.mountingRateHistory.length,1)});

test('rehydrating while already on settings restores rate availability only after successful login',async()=>{const a=app({session:authenticated});await a.ready();a.api.settings();a.signOut();await a.ready();assert.equal(a.online().canEditGoal(),false);await a.login();assert.equal(a.online().canEditGoal(),true);assert.equal(a.node('rate-button-a').disabled,false);assert.equal(a.node('mounting-rate-online-warning').hidden,true);assert.equal(a.rpcs.length,0)});
