'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const Assembly=require('../assembly-finance'),Dashboard=require('../dashboard-view'),Inventory=require('../inventory-guard');
const {state}=require('./fixtures/dashboard-state');
const html=fs.readFileSync(path.join(__dirname,'../index.html'),'utf8');
const scripts=[...html.matchAll(/<script([^>]*)>([\s\S]*?)<\/script>/g)].filter(m=>m[2].trim());
const TODAY='2026-10-07',NOW='2026-10-08T01:00:00Z';
function fixture(){const d=state();d.financeControl.version=1;return d}
function history(d=fixture()){return Assembly.addRate(d,{id:'rate-old',mountingId:'a',effectiveFrom:'2026-10-05',rateCents:260,createdAt:NOW})}
function app(input=fixture()){
 const nodes=new Map(),saved=[];let fail=false,focus=null;
 function node(id){if(!nodes.has(id))nodes.set(id,{id,innerHTML:'',textContent:'',value:'',hidden:id==='modal',disabled:false,isConnected:true,setAttribute(){},focus(){focus=id},querySelectorAll(){return[]}});return nodes.get(id)}
 const FixedDate=class extends Date{constructor(...args){super(...(args.length?args:[NOW]))}static now(){return new Date(NOW).getTime()}};
 const online={hasPending:()=>false,conflict:()=>false,onlineMode:true,canEditGoal:()=>true};
 const context=vm.createContext({Date:FixedDate,Intl,console,FioriAssembly:Assembly,FioriDashboard:Dashboard,FioriInventory:Inventory,document:{getElementById:node,querySelector:node,querySelectorAll(){return[]}},localStorage:{getItem:()=>JSON.stringify(input),setItem(k,v){if(fail)throw Error('Synthetic quota exceeded');saved.push({k,v})}},window:{fioriOnline:online},setTimeout(){},clearTimeout(){}});
 const main=scripts[0][2].slice(0,scripts[0][2].lastIndexOf('\ndocument.querySelectorAll("nav [role=tab]").forEach'));
 vm.runInContext(main+'\nglobalThis.api={getData:()=>data,settings:()=>switchTab("settings"),open:openMountingRate,saveOld:saveMountingRate,close:closeModal,render,renderSettings,shareText,renderWeek,weekSummary,replaceData:next=>{data=next;render()},leave:()=>switchTab("week"),attempt:()=>mountingRateAttempt,dropEngine:()=>{delete globalThis.FioriAssembly},reject:()=>{save=()=>false}};',context);
 function fields(date=TODAY,value='2,75'){node('mounting-rate-date').value=date;node('mounting-rate-value').value=value}
 function review(){node('mounting-rate-form').onsubmit({preventDefault(){}})}
 function confirm(){node('mounting-rate-confirm').onclick()}
 return {api:context.api,node,saved,online,fields,review,confirm,fail:value=>{fail=value},focused:()=>focus};
}
function opened(d){const a=app(d);a.api.settings();a.api.open('a',a.node('return-focus'));a.fields();return a}
test('opening, editing, previewing, cancelling and an old direct-rate handler never write',()=>{const a=opened(),before=JSON.stringify(a.api.getData());a.node('mounting-rate-value').oninput();assert.match(a.node('mounting-rate-preview').textContent,/2,75/);a.api.close();a.api.saveOld('a','9,99');assert.equal(a.api.attempt().value,'');assert.equal(a.saved.length,0);assert.equal(JSON.stringify(a.api.getData()),before)});
test('settings display the applicable rate today, not stale mounting cache or a future rate',()=>{let d=history();d=Assembly.addRate(d,{id:'future',mountingId:'a',effectiveFrom:'2026-10-09',rateCents:290,createdAt:NOW});const a=app(d),before=JSON.stringify(a.api.getData());a.api.settings();const text=a.node('tab-settings').innerHTML;assert.match(text,/2,60.*por par hoje/);assert.match(text,/De 05\/10\/2026 até 08\/10\/2026/);assert.match(text,/De 09\/10\/2026 em diante · futura/);assert.doesNotMatch(text,/data-rate-id/);assert.match(text,/Somente leitura/);assert.equal(JSON.stringify(a.api.getData()),before);assert.equal(a.saved.length,0)});
test('settings mark undated current fallback and missing rates without inventing dates',()=>{const a=app();a.api.settings();const text=a.node('tab-settings').innerHTML;assert.match(text,/Referência legada/);assert.match(text,/Nenhuma vigência cadastrada/);assert.match(text,/Sem tarifa aplicável hoje/);assert.match(a.node('modal-sheet').innerHTML,/^$/)});
test('inactive histories stay visible and cannot be changed',()=>{const d=history();d.settings.mountings[0].active=false;const a=app(d),before=JSON.stringify(a.api.getData());a.api.settings();const text=a.node('tab-settings').innerHTML;assert.match(text,/Montagem A \(teste\) · inativa/);assert.doesNotMatch(text,/data-define-rate="a"/);a.api.open('a');assert.equal(a.api.attempt(),null);assert.equal(JSON.stringify(a.api.getData()),before)});
test('confirming adds one history row while preserving old cache, snapshots, production and finance records',()=>{const a=opened(history()),before=JSON.parse(JSON.stringify(a.api.getData())),id=a.api.attempt().id;a.review();assert.equal(a.saved.length,0);a.confirm();const d=a.api.getData();assert.equal(a.saved.length,1);assert.equal(d.settings.mountingRateHistory.length,2);assert.equal(d.settings.mountingRateHistory[1].id,id);assert.equal(d.settings.mountingRateHistory[1].effectiveFrom,TODAY);assert.equal(d.settings.mountingRateHistory[1].rateCents,275);assert.equal(JSON.stringify(d.settings.mountings),JSON.stringify(before.settings.mountings));assert.equal(JSON.stringify(d.weeks),JSON.stringify(before.weeks));assert.equal(JSON.stringify(d.factoryExpenses),JSON.stringify(before.factoryExpenses));assert.equal(JSON.stringify(d.financeControl),JSON.stringify(before.financeControl));assert.equal(JSON.stringify(d.settings.mountingRateHistory[0]),JSON.stringify(before.settings.mountingRateHistory[0]))});
test('first rate activates baseline without fabricating production, obligations or payments',()=>{const d=fixture();d.weeks['2026-10-05'].entries.push({id:'old-finished',date:TODAY,kind:'finished',mountingId:'a',modelId:'m507',qty:1});const a=opened(d),before=JSON.stringify(a.api.getData().weeks);a.review();assert.match(a.node('modal-sheet').innerHTML,/protegido contra edição e exclusão/);a.confirm();const out=a.api.getData();assert.equal(out.assemblyControl.legacyFinishedIds[0],'old-finished');assert.equal(JSON.stringify(out.weeks),before);assert.equal(out.factoryExpenses.length,0);assert.equal(out.financeControl.settlements.length,0)});
test('future and retroactive explicit dates are accepted and previews show the next boundary',()=>{for(const date of ['2026-10-04','2026-10-12']){const a=opened(history());a.fields(date);a.node('mounting-rate-date').onchange();if(date<'2026-10-05')assert.match(a.node('mounting-rate-preview').textContent,/até 04\/10\/2026/);else assert.match(a.node('mounting-rate-preview').textContent,/Vigência futura/);a.review();a.confirm();assert.equal(a.api.getData().settings.mountingRateHistory.at(-1).effectiveFrom,date)}});
for(const [date,value]of [['','2,75'],['2026-02-30','2,75'],[TODAY,''],[TODAY,'0'],[TODAY,'-2'],[TODAY,'2,755'],[TODAY,'1e2'],[TODAY,'1.000,00'],[TODAY,'Infinity'],[TODAY,'999999999999999999999999']])test(`invalid input ${date}/${value} does not save or mutate`,()=>{const a=opened(),before=JSON.stringify(a.api.getData());a.fields(date,value);a.review();assert.equal(a.saved.length,0);assert.equal(a.api.attempt().phase,'form');assert.equal(a.node('mounting-rate-error').hidden,false);assert.equal(JSON.stringify(a.api.getData()),before)});
test('duplicate effective date is rejected before confirmation without a write',()=>{const a=opened(history()),before=JSON.stringify(a.api.getData());a.fields('2026-10-05');a.review();assert.match(a.node('mounting-rate-error').textContent,/Já existe uma tarifa/);assert.equal(JSON.stringify(a.api.getData()),before);assert.equal(a.saved.length,0)});
test('dot-decimal cents are exact and date default is today in Sao Paulo',()=>{const a=opened();assert.equal(a.api.attempt().date,TODAY);a.fields(TODAY,'0.01');a.review();a.confirm();assert.equal(a.api.getData().settings.mountingRateHistory[0].rateCents,1)});
test('double review and double confirm persist just one stable rate id',()=>{const a=opened(),id=a.api.attempt().id,review=a.node('mounting-rate-form').onsubmit;review({preventDefault(){}});const confirm=a.node('mounting-rate-confirm').onclick;review({preventDefault(){}});confirm();confirm();assert.equal(a.saved.length,1);assert.equal(a.api.getData().settings.mountingRateHistory[0].id,id)});
test('cancel form, confirmation, or return from confirmation invalidates old callbacks',()=>{for(const phase of ['form','confirm','back']){const a=opened(),before=JSON.stringify(a.api.getData());let stale;if(phase==='form')stale=()=>a.review();else{a.review();stale=a.node('mounting-rate-confirm').onclick}if(phase==='back')a.node('mounting-rate-back').onclick();else a.api.close();stale();assert.equal(a.saved.length,0);assert.equal(JSON.stringify(a.api.getData()),before)}});
test('back preserves typed values and the attempt ID',()=>{const a=opened(),id=a.api.attempt().id;a.fields('2026-10-09','2,98');a.review();a.node('mounting-rate-back').onclick();assert.equal(a.api.attempt().id,id);assert.equal(a.api.attempt().date,'2026-10-09');assert.equal(a.api.attempt().value,'2,98');assert.equal(a.saved.length,0)});
test('cancel restores focus and rate dialogs include labels, live preview and form semantics',()=>{const a=opened();const text=a.node('modal-sheet').innerHTML;for(const part of ['<form','for="mounting-rate-date"','for="mounting-rate-value"','aria-live="polite"','type="submit"'])assert.ok(text.includes(part));a.api.close();assert.equal(a.focused(),'return-focus')});
for(const mode of ['pending','conflict','unhydrated'])test(`${mode} blocks opening, review and final confirmation`,()=>{function block(a){if(mode==='unhydrated')a.online.canEditGoal=()=>false;else a.online[mode==='pending'?'hasPending':'conflict']=()=>true}const unopened=app();unopened.api.settings();block(unopened);unopened.api.open('a');assert.equal(unopened.api.attempt(),null);for(const phase of ['form','confirm']){const a=opened(),before=JSON.stringify(a.api.getData());if(phase==='confirm')a.review();block(a);if(phase==='form')a.review();else a.confirm();assert.equal(a.saved.length,0);assert.equal(JSON.stringify(a.api.getData()),before)}});
test('data mutation during form or confirmation invalidates the operation',()=>{for(const phase of ['form','confirm']){const a=opened();if(phase==='confirm')a.review();a.api.getData().settings.mountings[0].name='Updated elsewhere';const before=JSON.stringify(a.api.getData());if(phase==='form')a.review();else a.confirm();assert.equal(a.saved.length,0);assert.equal(JSON.stringify(a.api.getData()),before);assert.match(a.node('toast').textContent,/dados mudaram/)}});
test('rerender, changing tabs and remote replacement invalidate retained callbacks and close dialog',()=>{for(const change of ['render','settings','tab','remote'])for(const phase of ['form','confirm']){const a=opened();let stale;if(phase==='confirm'){a.review();stale=a.node('mounting-rate-confirm').onclick}else stale=()=>a.review();if(change==='render')a.api.render();if(change==='settings')a.api.renderSettings();if(change==='tab')a.api.leave();if(change==='remote')a.api.replaceData(fixture());stale();assert.equal(a.saved.length,0);assert.equal(a.node('modal').hidden,true);assert.equal(a.api.attempt(),null)}});
test('newer dialog invalidates older callbacks even on the same mounting',()=>{const a=opened();a.review();const old=a.node('mounting-rate-confirm').onclick;a.api.open('a');old();assert.equal(a.saved.length,0);assert.equal(a.api.attempt().phase,'form')});
test('quota failure rolls back, preserves attempt ID and values and permits a reviewed retry',()=>{const a=opened(),before=JSON.stringify(a.api.getData()),id=a.api.attempt().id;a.fail(true);a.review();const old=a.node('mounting-rate-confirm').onclick;old();assert.equal(a.saved.length,0);assert.equal(JSON.stringify(a.api.getData()),before);assert.equal(a.api.attempt().id,id);assert.equal(a.api.attempt().phase,'form');assert.match(a.node('mounting-rate-error').textContent,/não foi salva/);a.fail(false);a.fields();old();assert.equal(a.saved.length,0);a.review();a.confirm();assert.equal(a.saved.length,1);assert.equal(a.api.getData().settings.mountingRateHistory[0].id,id)});
test('explicit save false leaves the original state and reopens reviewable form',()=>{const a=opened(),before=JSON.stringify(a.api.getData());a.api.reject();a.review();a.confirm();assert.equal(a.saved.length,0);assert.equal(JSON.stringify(a.api.getData()),before);assert.equal(a.api.attempt().phase,'form')});
test('settings escape names, missing engine fails closed, and cache/version are current',()=>{const d=fixture();d.settings.mountings[0].name='<img src=x onerror=alert(1)>';const a=app(d);a.api.settings();assert.doesNotMatch(a.node('tab-settings').innerHTML,/<img src=x/);assert.match(html,/v2026\.10\.08-r8\.3/);assert.match(fs.readFileSync(path.join(__dirname,'../sw.js'),'utf8'),/shell-v31/)});
test('weekly view and share text sum per-entry frozen and numeric legacy rates across midweek changes',()=>{let d=history();d=Assembly.addRate(d,{id:'rate-new',mountingId:'a',effectiveFrom:TODAY,rateCents:275,createdAt:NOW});for(const [id,date,qty]of [['first','2026-10-06',10],['second',TODAY,20]])d=Assembly.createFinished(d,{id,date,qty,kind:'finished',mountingId:'a',modelId:'m507'},{today:TODAY,now:NOW});d.weeks['2026-10-05'].entries.push({id:'legacy',date:'2026-10-05',qty:5,kind:'finished',mountingId:'a',modelId:'m507',mountingRate:2.5},{id:'estimate',date:'2026-10-06',qty:3,kind:'finished',mountingId:'a',modelId:'m507'},{id:'future-entry',date:'2026-10-09',qty:100,kind:'finished',mountingId:'a',modelId:'m507',mountingRate:99});const a=app(d),before=JSON.stringify(a.api.getData()),summary=a.api.weekSummary('2026-10-05'),row=summary.mountingValues.mountings.find(m=>m.id==='a');assert.equal(row.totalPairs,38);assert.equal(row.knownCents,9350);assert.equal(row.estimatedCents,780);a.api.renderWeek();for(const text of [a.node('tab-week').innerHTML,a.api.shareText()]){assert.match(text,/93,50/);assert.match(text,/Estimativa:.*7,80/);assert.match(text,/sem tarifa congelada/);assert.doesNotMatch(text,/9\.900,00/)}assert.equal(JSON.stringify(a.api.getData()),before);assert.equal(a.saved.length,0)});
test('archived week keeps legacy snapshots and identifies fallback as estimation rather than debt',()=>{const d=fixture();d.weeks['2026-09-28'].mountingSnapshot=JSON.parse(JSON.stringify(d.settings.mountings));d.weeks['2026-09-28'].mountingSnapshot[0].rate=1.7;d.settings.mountings[0].rate=9;d.weeks['2026-09-28'].entries=[{id:'historic-known',date:'2026-09-30',qty:10,kind:'finished',mountingId:'a',mountingRate:1.6},{id:'historic-unknown',date:'2026-10-01',qty:5,kind:'finished',mountingId:'a'}];const a=app(d),before=JSON.stringify(a.api.getData());a.api.renderWeek('2026-09-28');const text=a.node('tab-week').innerHTML;assert.match(text,/16,00/);assert.match(text,/Estimativa:.*8,50/);assert.match(text,/Não informa saldo a pagar nem gera custo ou dívida/);assert.equal(JSON.stringify(a.api.getData()),before);assert.equal(a.saved.length,0)});
test('weekly missing rates and invalid amounts are visibly unpriced, never silently zero',()=>{const d=fixture();d.weeks['2026-10-05'].entries.push({id:'unpriced',date:TODAY,qty:3,kind:'finished',mountingId:'empty'},{id:'bad-snapshot',date:TODAY,qty:2,kind:'finished',mountingId:'a',assemblyRate:{rateCents:0}});const a=app(d);a.api.renderWeek();for(const text of [a.node('tab-week').innerHTML,a.api.shareText()]){assert.match(text,/3 pares sem valor calculável/);assert.match(text,/2 pares sem valor calculável/);assert.match(text,/Há registros para conferir/)}assert.equal(a.saved.length,0)});

test('missing rate engine fails closed in settings and opening cannot save',()=>{const a=app(),before=JSON.stringify(a.api.getData());a.api.dropEngine();a.api.settings();assert.match(a.node('tab-settings').innerHTML,/Recarregue o app para carregar as tarifas/);assert.match(a.node('tab-settings').innerHTML,/data-define-rate="a" disabled/);a.api.open('a');assert.equal(a.api.attempt(),null);assert.equal(a.saved.length,0);assert.equal(JSON.stringify(a.api.getData()),before)});
